In [ ]:
import pandas as pd
import numpy as np

: 

In [ ]:
df = pd.read_csv('ClassicHit.csv')

: 

In [5]:
df.head()

Track          Artist  Year  Duration  Time_Signature  \
0         Hey Jack Kerouac  10,000 Maniacs  1987    206413               4   
1         Like the Weather  10,000 Maniacs  1987    236653               4   
2  What's the Matter Here?  10,000 Maniacs  1987    291173               4   
3               Trouble Me  10,000 Maniacs  1989    193560               4   
4    Candy Everybody Wants  10,000 Maniacs  1992    185960               4   

   Danceability  Energy  Key  Loudness  Mode  Speechiness  Acousticness  \
0         0.616   0.511    6   -15.894     1       0.0279       0.03840   
1         0.770   0.459    1   -17.453     1       0.0416       0.11200   
2         0.593   0.816    9    -7.293     1       0.0410       0.00449   
3         0.861   0.385    2   -10.057     1       0.0341       0.15400   
4         0.622   0.876   10    -6.310     1       0.0305       0.01930   

   Instrumentalness  Liveness  Valence    Tempo  Popularity      Genre  
0          0.000000    0.1500    0.604  132.015          40  Alt. Rock  
1          0.003430    0.1450    0.963  133.351          43  Alt. Rock  
2          0.000032    0.0896    0.519   99.978          12  Alt. Rock  
3          0.000000    0.1230    0.494  117.913          47  Alt. Rock  
4          0.006840    0.0987    0.867  104.970          43  Alt. Rock

In [6]:
df.describe()

Year      Duration  Time_Signature  Danceability        Energy  \
count  15150.000000  1.515000e+04    15150.000000  15150.000000  15150.000000   
mean    1984.709769  2.413028e+05        3.921650      0.574667      0.617691   
std       19.482460  1.057966e+05        0.348322      0.166208      0.239527   
min     1899.000000  2.300000e+04        0.000000      0.000000      0.000098   
25%     1971.000000  1.803700e+05        4.000000      0.461000      0.442000   
50%     1983.000000  2.228525e+05        4.000000      0.582000      0.644000   
75%     1998.000000  2.751530e+05        4.000000      0.696000      0.819000   
max     2024.000000  3.060650e+06        5.000000      0.988000      0.999000   

                Key      Loudness          Mode   Speechiness  Acousticness  \
count  15150.000000  15150.000000  15150.000000  15150.000000  15150.000000   
mean       5.257624     -9.154545      0.696634      0.075791      0.302651   
std        3.569713      4.289558      0.459727      0.077704      0.317793   
min        0.000000    -47.359000      0.000000      0.000000      0.000001   
25%        2.000000    -11.736750      0.000000      0.034325      0.024225   
50%        5.000000     -8.480500      1.000000      0.046400      0.167000   
75%        8.000000     -5.955500      1.000000      0.078400      0.557000   
max       11.000000      0.919000      1.000000      0.950000      0.996000   

       Instrumentalness      Liveness       Valence         Tempo  \
count      15150.000000  15150.000000  15150.000000  15150.000000   
mean           0.091046      0.200062      0.571146    120.664078   
std            0.229075      0.175196      0.250969     29.181107   
min            0.000000      0.012400      0.000000      0.000000   
25%            0.000000      0.091900      0.371000     98.672500   
50%            0.000084      0.130000      0.586000    118.777000   
75%            0.012400      0.257000      0.782000    138.073250   
max            0.987000      0.996000      0.989000    219.973000   

         Popularity  
count  15150.000000  
mean      43.025809  
std       20.788038  
min        0.000000  
25%       28.000000  
50%       44.000000  
75%       59.000000  
max       98.000000

In [7]:
df.shape

(15150, 18)

In [8]:
df.isnull().sum()

Track               0
Artist              0
Year                0
Duration            0
Time_Signature      0
Danceability        0
Energy              0
Key                 0
Loudness            0
Mode                0
Speechiness         0
Acousticness        0
Instrumentalness    0
Liveness            0
Valence             0
Tempo               0
Popularity          0
Genre               0
dtype: int64

In [9]:
df.duplicated().sum()

1

In [10]:
df.drop_duplicates()

Track          Artist  Year  Duration  \
0                    Hey Jack Kerouac  10,000 Maniacs  1987    206413   
1                    Like the Weather  10,000 Maniacs  1987    236653   
2             What's the Matter Here?  10,000 Maniacs  1987    291173   
3                          Trouble Me  10,000 Maniacs  1989    193560   
4               Candy Everybody Wants  10,000 Maniacs  1992    185960   
...                               ...             ...   ...       ...   
15145  7 Seconds (feat. Neneh Cherry)  Youssou N'Dour  1994    306226   
15146                          Birima  Youssou N'Dour  1995    228373   
15147                             Set  Youssou N'Dour  2004    226826   
15148                Africa Remembers  Youssou N'Dour  2007    560466   
15149                       Wiri-Wiri  Youssou N'Dour  2007    247466   

       Time_Signature  Danceability  Energy  Key  Loudness  Mode  Speechiness  \
0                   4         0.616   0.511    6   -15.894     1       0.0279   
1                   4         0.770   0.459    1   -17.453     1       0.0416   
2                   4         0.593   0.816    9    -7.293     1       0.0410   
3                   4         0.861   0.385    2   -10.057     1       0.0341   
4                   4         0.622   0.876   10    -6.310     1       0.0305   
...               ...           ...     ...  ...       ...   ...          ...   
15145               4         0.679   0.659    1   -10.826     0       0.0269   
15146               4         0.692   0.737   10    -7.042     1       0.0512   
15147               4         0.733   0.730    0   -11.056     1       0.0479   
15148               4         0.696   0.378    5   -16.181     0       0.0797   
15149               4         0.654   0.516    5   -10.325     1       0.0707   

       Acousticness  Instrumentalness  Liveness  Valence    Tempo  Popularity  \
0           0.03840          0.000000    0.1500    0.604  132.015          40   
1           0.11200          0.003430    0.1450    0.963  133.351          43   
2           0.00449          0.000032    0.0896    0.519   99.978          12   
3           0.15400          0.000000    0.1230    0.494  117.913          47   
4           0.01930          0.006840    0.0987    0.867  104.970          43   
...             ...               ...       ...      ...      ...         ...   
15145       0.07710          0.000004    0.3160    0.528  154.171          47   
15146       0.25400          0.017400    0.1120    0.808  105.754          18   
15147       0.04240          0.000101    0.0282    0.840  146.213          25   
15148       0.44400          0.019400    0.0850    0.551   97.677           8   
15149       0.30400          0.000235    0.1100    0.259   83.013           5   

           Genre  
0      Alt. Rock  
1      Alt. Rock  
2      Alt. Rock  
3      Alt. Rock  
4      Alt. Rock  
...          ...  
15145      World  
15146      World  
15147      World  
15148      World  
15149      World  

[15149 rows x 18 columns]

In [11]:
mood_ranges = {
    "Happy": {
        "danceability": (0.7, 1.0),
        "energy": (0.7, 1.0),
        "valence": (0.7, 1.0),
        "loudness": (-6, 0),
        "acousticness": (0.0, 0.3),
        "tempo": (100, 140),
        "mode": 1
    },
    "Sad": {
        "danceability": (0.0, 0.5),
        "energy": (0.2, 0.5),
        "valence": (0.0, 0.4),
        "loudness": (-30, -8),
        "acousticness": (0.4, 1.0),
        "tempo": (60, 90),
        "mode": 0
    },
    "Angry": {
        "danceability": (0.4, 0.7),
        "energy": (0.8, 1.0),
        "valence": (0.0, 0.3),
        "loudness": (-5, 0),
        "acousticness": (0.0, 0.2),
        "tempo": (110, 160),
        "mode": 0
    },
    "Disgust": {
        "danceability": (0.0, 0.5),
        "energy": (0.3, 0.6),
        "valence": (0.0, 0.3),
        "loudness": (-12, -6),
        "acousticness": (0.4, 0.9),
        "tempo": (60, 100),
        "mode": 0
    },
    "Fear": {
        "danceability": (0.0, 0.4),
        "energy": (0.4, 0.8),
        "valence": (0.0, 0.3),
        "loudness": (-15, -8),
        "acousticness": (0.3, 0.7),
        "tempo": (70, 120),
        "mode": 0
    },
    "Neutral": {
        "danceability": (0.4, 0.6),
        "energy": (0.4, 0.6),
        "valence": (0.4, 0.6),
        "loudness": (-10, -6),
        "acousticness": (0.2, 0.6),
        "tempo": (80, 120),
        "mode": 1  # or 0, both acceptable
    },
    "Surprise": {
        "danceability": (0.6, 1.0),
        "energy": (0.7, 1.0),
        "valence": (0.5, 0.9),
        "loudness": (-6, 0),
        "acousticness": (0.0, 0.4),
        "tempo": (110, 150),
        "mode": 1
    }
}

In [12]:
df_new = df.copy()

In [13]:
print(df_new.columns.tolist())

['Track', 'Artist', 'Year', 'Duration', 'Time_Signature', 'Danceability', 'Energy', 'Key', 'Loudness', 'Mode', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo', 'Popularity', 'Genre']


In [14]:
df_new.drop(columns=['Time_Signature', 'Key', 'Speechiness', 'Instrumentalness'], inplace=True)

In [15]:
df_new.head()

Track          Artist  Year  Duration  Danceability  \
0         Hey Jack Kerouac  10,000 Maniacs  1987    206413         0.616   
1         Like the Weather  10,000 Maniacs  1987    236653         0.770   
2  What's the Matter Here?  10,000 Maniacs  1987    291173         0.593   
3               Trouble Me  10,000 Maniacs  1989    193560         0.861   
4    Candy Everybody Wants  10,000 Maniacs  1992    185960         0.622   

   Energy  Loudness  Mode  Acousticness  Liveness  Valence    Tempo  \
0   0.511   -15.894     1       0.03840    0.1500    0.604  132.015   
1   0.459   -17.453     1       0.11200    0.1450    0.963  133.351   
2   0.816    -7.293     1       0.00449    0.0896    0.519   99.978   
3   0.385   -10.057     1       0.15400    0.1230    0.494  117.913   
4   0.876    -6.310     1       0.01930    0.0987    0.867  104.970   

   Popularity      Genre  
0          40  Alt. Rock  
1          43  Alt. Rock  
2          12  Alt. Rock  
3          47  Alt. Rock  
4          43  Alt. Rock

In [16]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def select_mood(mood_range, mood):
    ranges = mood_range[mood]
    
    input_vector = []

    for key, value in ranges.items():
        if isinstance(value, tuple):
            input_vector.append(np.random.uniform(value[0], value[1]))
        else:
            input_vector.append(value)
    
    input_vector = np.array(input_vector).reshape(1, -1)
    return input_vector


In [17]:
select_mood(mood_ranges,"Happy")

array([[  0.7465873 ,   0.76511083,   0.89164115,  -5.51269   ,
          0.18021263, 139.07574636,   1.        ]])

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

In [25]:
features = df_new[['Danceability', 'Energy', 'Loudness', 'Mode', 'Acousticness', 'Valence', 'Tempo']]
scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(features)

In [28]:
def select_n_songs(scaled_features,mood_vector):
    scaled_input = scaler.transform(mood_vector)

    similarities = cosine_similarity(scaled_input, scaled_features)[0]

    top_indices = similarities.argsort()[::-1][:5]
    top_scores = similarities[top_indices]
    top_songs = df.iloc[top_indices].copy()
    print(top_indices)
    print(top_scores)
    print(top_songs['Track'])
    

In [29]:
select_n_songs(scaled_features,select_mood(mood_ranges,"Happy"))

[14977 10984  9713  5337  2349]
[0.71471471 0.6464144  0.6393785  0.63906407 0.63431231]
14977              Funky Nassau
10984                   Peaches
9713           Hello,I Love You
5337                 The Kicker
2349     Playing Your Game,Baby
Name: Track, dtype: object


C:\ProgramData\anaconda3\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
